name: Build
on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: yarn install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: yarn build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: yarn test
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test
        